"""Sieve script generation from config rules."""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Sequence

from mailfilter.config import Config, Rule


def sieve_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _group_rules_by_domain(rules: list[Rule], folder_prefix: str) -> dict[str, list[str]]:
    """Group active rules by domain, returning {domain: [local_part, ...]}.

    Only includes rules whose folder matches ``folder_prefix/{local_part}``
    (i.e. rules that fit the envelope variable-routing pattern).
    """
    by_domain: dict[str, list[str]] = defaultdict(list)
    seen: dict[str, set[str]] = defaultdict(set)
    for rule in rules:
        if not rule.active:
            continue
        for alias in rule.aliases:
            if "@" not in alias:
                continue
            local, domain = alias.rsplit("@", 1)
            local_lower = local.lower()
            expected_folder = f"{folder_prefix}/{local_lower}"
            if rule.folder != expected_folder:
                continue
            if local_lower not in seen[domain]:
                by_domain[domain].append(local_lower)
                seen[domain].add(local_lower)
    return dict(by_domain)


def generate_sieve_envelope(config: Config) -> str:
    """Generate a compact Sieve script using envelope + variables extensions."""
    requires = ["fileinto"]
    if config.use_create:
        requires.append("mailbox")
    requires.extend(["envelope", "variables"])

    grouped = _group_rules_by_domain([r for r in config.rules if r.active], config.folder_prefix)

    parts: list[str] = [
        "# Generated by mailfilter",
        f"require [{', '.join(sieve_quote(x) for x in requires)}];",
        "",
    ]

    for domain, locals_ in grouped.items():
        alias_list = ", ".join(sieve_quote(lp) for lp in sorted(locals_))
        create_flag = ":create " if config.use_create else ""
        parts.append(f'if envelope :domain :is "to" {sieve_quote(domain)} {{')
        parts.append('    if envelope :localpart :matches "to" "*" {')
        parts.append('        set :lower "alias" "${1}";')
        parts.append(f'        if string :is "${{alias}}" [{alias_list}] {{')
        parts.append(f"            fileinto {create_flag}{sieve_quote(config.folder_prefix + '/${alias}')};")
        parts.append("            stop;")
        parts.append("        }")
        if config.catch_all_folder:
            parts.append(f"        fileinto {create_flag}{sieve_quote(config.catch_all_folder)};")
            parts.append("        stop;")
        parts.append("    }")
        parts.append("}")
        parts.append("")

    if config.explicit_keep:
        parts.append("keep;")

    return "\n".join(parts).strip() + "\n"


def generate_rule_block(rule: Rule, headers: Sequence[str], match_type: str, use_create: bool) -> str:
    effective_headers = rule.headers if rule.headers else headers
    tests: list[str] = []
    for alias in rule.aliases:
        for header in effective_headers:
            tests.append(f"header :{match_type} {sieve_quote(header)} {sieve_quote(alias)}")

    condition = tests[0] if len(tests) == 1 else "anyof (\n        " + ",\n        ".join(tests) + "\n    )"

    fileinto = f"fileinto {':create ' if use_create else ''}{sieve_quote(rule.folder)};"

    lines: list[str] = []
    if rule.comment:
        lines.append(f"# {rule.comment}")
    lines.append(f"if {condition} {{")
    lines.append(f"    {fileinto}")
    lines.append("    stop;")
    lines.append("}")
    return "\n".join(lines)


def generate_sieve(config: Config) -> str:
    if config.generation_mode == "envelope":
        return generate_sieve_envelope(config)

    requires = ["fileinto"]
    if config.use_create:
        requires.append("mailbox")
    if config.match_type == "regex":
        requires.append("regex")

    active_rules = [r for r in config.rules if r.active]

    parts = [
        "# Generated by mailfilter",
        f"require [{', '.join(sieve_quote(x) for x in requires)}];",
        "",
    ]

    for idx, rule in enumerate(active_rules):
        parts.append(generate_rule_block(rule, config.headers, config.match_type, config.use_create))
        if idx != len(active_rules) - 1:
            parts.append("")

    if config.explicit_keep:
        parts.append("")
        parts.append("keep;")

    return "\n".join(parts).strip() + "\n"
