"""Sieve script generation from config rules."""

from __future__ import annotations

from collections.abc import Sequence

from mailfilter.config import Config, Rule


def sieve_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate_rule_block(rule: Rule, headers: Sequence[str], match_type: str, use_create: bool) -> str:
    effective_headers = rule.headers if rule.headers else headers
    tests: list[str] = []
    for alias in rule.aliases:
        for header in effective_headers:
            tests.append(f"header :{match_type} {sieve_quote(header)} {sieve_quote(alias)}")

    condition = tests[0] if len(tests) == 1 else "anyof (\n        " + ",\n        ".join(tests) + "\n    )"

    fileinto = f"fileinto {':create ' if use_create else ''}{sieve_quote(rule.folder)};"

    lines: list[str] = []
    if rule.comment:
        lines.append(f"# {rule.comment}")
    lines.append(f"if {condition} {{")
    lines.append(f"    {fileinto}")
    lines.append("    stop;")
    lines.append("}")
    return "\n".join(lines)


def generate_sieve(config: Config) -> str:
    requires = ["fileinto"]
    if config.use_create:
        requires.append("mailbox")
    if config.match_type == "regex":
        requires.append("regex")

    active_rules = [r for r in config.rules if r.active]

    parts = [
        "# Generated by mailfilter",
        f"require [{', '.join(sieve_quote(x) for x in requires)}];",
        "",
    ]

    for idx, rule in enumerate(active_rules):
        parts.append(generate_rule_block(rule, config.headers, config.match_type, config.use_create))
        if idx != len(active_rules) - 1:
            parts.append("")

    if config.explicit_keep:
        parts.append("")
        parts.append("keep;")

    return "\n".join(parts).strip() + "\n"
