"""Tests for mailfilter.sieve."""

from __future__ import annotations

from mailfilter.config import Config, Rule
from mailfilter.sieve import (
    _group_rules_by_domain,
    generate_rule_block,
    generate_sieve,
    generate_sieve_envelope,
    generate_sieve_fallback,
    partition_envelope_rules,
    sieve_quote,
)


class TestSieveQuote:
    def test_plain_string(self):
        assert sieve_quote("hello") == '"hello"'

    def test_backslash(self):
        assert sieve_quote("a\\b") == '"a\\\\b"'

    def test_double_quote(self):
        assert sieve_quote('say "hi"') == '"say \\"hi\\""'

    def test_empty(self):
        assert sieve_quote("") == '""'


class TestGenerateRuleBlock:
    def test_single_alias_single_header(self):
        rule = Rule(aliases=["a@b.com"], folder="F")
        block = generate_rule_block(rule, headers=["To"], match_type="is", use_create=False)
        assert 'header :is "To" "a@b.com"' in block
        assert "anyof" not in block
        assert 'fileinto "F";' in block
        assert "stop;" in block

    def test_multiple_aliases_uses_anyof(self):
        rule = Rule(aliases=["a@b.com", "c@b.com"], folder="F")
        block = generate_rule_block(rule, headers=["To"], match_type="is", use_create=False)
        assert "anyof" in block

    def test_multiple_headers_uses_anyof(self):
        rule = Rule(aliases=["a@b.com"], folder="F")
        block = generate_rule_block(rule, headers=["X-Original-To", "Delivered-To"], match_type="is", use_create=False)
        assert "anyof" in block
        assert '"X-Original-To"' in block
        assert '"Delivered-To"' in block

    def test_use_create(self):
        rule = Rule(aliases=["a@b.com"], folder="F")
        block = generate_rule_block(rule, headers=["To"], match_type="is", use_create=True)
        assert "fileinto :create" in block

    def test_contains_match(self):
        rule = Rule(aliases=["a@b.com"], folder="F")
        block = generate_rule_block(rule, headers=["To"], match_type="contains", use_create=False)
        assert ":contains" in block

    def test_comment(self):
        rule = Rule(aliases=["a@b.com"], folder="F", comment="My rule")
        block = generate_rule_block(rule, headers=["To"], match_type="is", use_create=False)
        assert block.startswith("# My rule")

    def test_per_rule_headers(self):
        rule = Rule(aliases=["a@b.com"], folder="F", headers=["X-Original-To"])
        block = generate_rule_block(rule, headers=["To", "Delivered-To"], match_type="is", use_create=False)
        assert '"X-Original-To"' in block
        assert '"To"' not in block
        assert '"Delivered-To"' not in block

    def test_regex_match(self):
        rule = Rule(aliases=[".*@sub.example.com"], folder="F")
        block = generate_rule_block(rule, headers=["To"], match_type="regex", use_create=False)
        assert ':regex "To"' in block

    def test_matches_match(self):
        rule = Rule(aliases=["*@sub.example.com"], folder="F")
        block = generate_rule_block(rule, headers=["To"], match_type="matches", use_create=False)
        assert ':matches "To"' in block


class TestGenerateSieve:
    def _config(self, **overrides) -> Config:
        defaults = {
            "headers": ["X-Original-To", "Delivered-To"],
            "use_create": True,
            "script_name": "test",
            "explicit_keep": False,
            "match_type": "is",
            "rules": [
                Rule(aliases=["a@b.com"], folder="Folder/A"),
            ],
        }
        defaults.update(overrides)
        return Config(**defaults)

    def test_require_fileinto(self):
        config = self._config(use_create=False)
        sieve = generate_sieve(config)
        assert 'require ["fileinto"];' in sieve
        assert '"mailbox"' not in sieve

    def test_require_mailbox_when_create(self):
        config = self._config(use_create=True)
        sieve = generate_sieve(config)
        assert '"mailbox"' in sieve

    def test_explicit_keep(self):
        config = self._config(explicit_keep=True)
        sieve = generate_sieve(config)
        assert sieve.strip().endswith("keep;")

    def test_no_keep_by_default(self):
        config = self._config(explicit_keep=False)
        sieve = generate_sieve(config)
        assert "keep;" not in sieve

    def test_generated_header(self):
        config = self._config()
        sieve = generate_sieve(config)
        assert sieve.startswith("# Generated by autosieve")

    def test_ends_with_newline(self):
        config = self._config()
        sieve = generate_sieve(config)
        assert sieve.endswith("\n")

    def test_multiple_rules(self):
        config = self._config(
            rules=[
                Rule(aliases=["a@b.com"], folder="A"),
                Rule(aliases=["c@b.com"], folder="C"),
            ]
        )
        sieve = generate_sieve(config)
        assert sieve.count("fileinto :create") == 2
        assert sieve.count("stop;") == 2

    def test_sample_output_structure(self, sample_config_path):
        """Generate from sample config and verify structural correctness."""
        from mailfilter.config import load_alias_config

        config = load_alias_config(sample_config_path)
        sieve = generate_sieve(config)

        # Must have require line with both fileinto and mailbox.
        assert 'require ["fileinto", "mailbox"];' in sieve
        # Must have two rule blocks.
        assert sieve.count("fileinto :create") == 2
        assert sieve.count("stop;") == 2

    def test_same_folder_rules_merged_in_sieve(self, tmp_path):
        """Two JSON rules mapping to the same folder produce ONE sieve if-block."""
        import json

        from mailfilter.config import load_alias_config

        data = {
            "rules": [
                {"alias": "a@b.com", "folder": "Work"},
                {"alias": "c@b.com", "folder": "Work"},
            ]
        }
        p = tmp_path / "cfg.json"
        p.write_text(json.dumps(data))
        config = load_alias_config(p)
        sieve = generate_sieve(config)
        # Only one fileinto / one stop => one if-block.
        assert sieve.count('fileinto "Work";') == 1
        assert sieve.count("stop;") == 1
        # Both aliases appear in the same anyof block.
        assert '"a@b.com"' in sieve
        assert '"c@b.com"' in sieve
        assert "anyof" in sieve

    def test_inactive_rules_skipped(self):
        config = self._config(
            rules=[
                Rule(aliases=["a@b.com"], folder="A"),
                Rule(aliases=["c@b.com"], folder="C", active=False),
            ]
        )
        sieve = generate_sieve(config)
        assert '"a@b.com"' in sieve
        assert '"c@b.com"' not in sieve
        assert sieve.count("stop;") == 1

    def test_all_inactive_produces_no_rules(self):
        config = self._config(rules=[Rule(aliases=["a@b.com"], folder="A", active=False)])
        sieve = generate_sieve(config)
        assert "stop;" not in sieve
        assert "# Generated by autosieve" in sieve

    def test_require_regex(self):
        config = self._config(match_type="regex")
        sieve = generate_sieve(config)
        assert '"regex"' in sieve
        assert ":regex" in sieve

    def test_matches_no_extra_require(self):
        config = self._config(match_type="matches")
        sieve = generate_sieve(config)
        assert ":matches" in sieve
        assert '"regex"' not in sieve


class TestGroupRulesByDomain:
    def test_single_domain(self):
        rules = [
            Rule(aliases=["alice@example.com"], folder="alias/alice"),
            Rule(aliases=["bob@example.com"], folder="alias/bob"),
        ]
        grouped = _group_rules_by_domain(rules, "alias")
        assert grouped == {"example.com": {"alias/${alias}": ["alice", "bob"]}}

    def test_multi_domain(self):
        rules = [
            Rule(aliases=["alice@a.com"], folder="alias/alice"),
            Rule(aliases=["bob@b.com"], folder="alias/bob"),
        ]
        grouped = _group_rules_by_domain(rules, "alias")
        assert "a.com" in grouped
        assert "b.com" in grouped

    def test_skips_mismatched_folder(self):
        rules = [
            Rule(aliases=["alice@example.com"], folder="alias/alice"),
            Rule(aliases=["logitell@example.com"], folder="alias/logitel"),
        ]
        grouped = _group_rules_by_domain(rules, "alias")
        assert grouped == {"example.com": {"alias/${alias}": ["alice"]}}

    def test_skips_inactive(self):
        rules = [
            Rule(aliases=["alice@example.com"], folder="alias/alice"),
            Rule(aliases=["bob@example.com"], folder="alias/bob", active=False),
        ]
        grouped = _group_rules_by_domain(rules, "alias")
        assert grouped == {"example.com": {"alias/${alias}": ["alice"]}}

    def test_skips_no_at(self):
        rules = [Rule(aliases=["noat"], folder="alias/noat")]
        grouped = _group_rules_by_domain(rules, "alias")
        assert grouped == {}

    def test_custom_prefix(self):
        rules = [Rule(aliases=["alice@example.com"], folder="mail/alice")]
        grouped = _group_rules_by_domain(rules, "mail")
        assert grouped == {"example.com": {"mail/${alias}": ["alice"]}}

    def test_deduplicates(self):
        rules = [
            Rule(aliases=["alice@example.com", "ALICE@example.com"], folder="alias/alice"),
        ]
        grouped = _group_rules_by_domain(rules, "alias")
        assert grouped == {"example.com": {"alias/${alias}": ["alice"]}}

    def test_discovers_nested_template(self):
        rules = [Rule(aliases=["shop@example.com"], folder="alias/shops/shop")]
        grouped = _group_rules_by_domain(rules, "alias")
        assert grouped == {"example.com": {"alias/shops/${alias}": ["shop"]}}


class TestGenerateSieveEnvelope:
    def _config(self, **overrides) -> Config:
        defaults = {
            "headers": ["X-Original-To"],
            "use_create": True,
            "script_name": "test",
            "explicit_keep": False,
            "match_type": "is",
            "generation_mode": "envelope",
            "folder_prefix": "alias",
            "folder_sep": "/",
            "catch_all_folder": None,
            "rules": [
                Rule(aliases=["alice@example.com"], folder="alias/alice"),
                Rule(aliases=["bob@example.com"], folder="alias/bob"),
            ],
        }
        defaults.update(overrides)
        return Config(**defaults)

    def test_requires_variables_not_envelope(self):
        config = self._config()
        sieve = generate_sieve_envelope(config)
        assert '"variables"' in sieve
        assert '"fileinto"' in sieve
        assert '"mailbox"' in sieve
        assert '"envelope"' not in sieve

    def test_requires_no_mailbox_without_create(self):
        config = self._config(use_create=False)
        sieve = generate_sieve_envelope(config)
        assert '"mailbox"' not in sieve

    def test_domain_block_uses_address(self):
        config = self._config()
        sieve = generate_sieve_envelope(config)
        assert 'address :domain :is "To" "example.com"' in sieve
        assert "envelope" not in sieve

    def test_localpart_matches_uses_address(self):
        config = self._config()
        sieve = generate_sieve_envelope(config)
        assert 'address :localpart :matches "To" "*"' in sieve

    def test_set_lower(self):
        config = self._config()
        sieve = generate_sieve_envelope(config)
        assert 'set :lower "alias" "${1}"' in sieve

    def test_string_is_aliases(self):
        config = self._config()
        sieve = generate_sieve_envelope(config)
        assert 'string :is "${alias}"' in sieve
        assert '"alice"' in sieve
        assert '"bob"' in sieve

    def test_alias_list_multiline_for_multiple(self):
        config = self._config()
        sieve = generate_sieve_envelope(config)
        # Multiple aliases → list spans multiple lines
        assert '"alice",\n' in sieve or '\"alice\",\n' in sieve

    def test_alias_list_inline_for_single(self):
        config = self._config(rules=[Rule(aliases=["alice@example.com"], folder="alias/alice")])
        sieve = generate_sieve_envelope(config)
        assert 'string :is "${alias}" ["alice"]' in sieve

    def test_fileinto_variable(self):
        config = self._config()
        sieve = generate_sieve_envelope(config)
        assert 'fileinto :create "alias/${alias}"' in sieve

    def test_fileinto_no_create(self):
        config = self._config(use_create=False)
        sieve = generate_sieve_envelope(config)
        assert 'fileinto "alias/${alias}"' in sieve
        assert ":create" not in sieve

    def test_catch_all(self):
        config = self._config(catch_all_folder="alias/_other")
        sieve = generate_sieve_envelope(config)
        assert 'fileinto :create "alias/_other"' in sieve

    def test_no_catch_all(self):
        config = self._config(catch_all_folder=None)
        sieve = generate_sieve_envelope(config)
        assert 'fileinto :create "alias/_other"' in sieve

    def test_explicit_keep(self):
        config = self._config(explicit_keep=True)
        sieve = generate_sieve_envelope(config)
        assert sieve.strip().endswith("keep;")

    def test_no_keep_by_default(self):
        config = self._config(explicit_keep=False)
        sieve = generate_sieve_envelope(config)
        assert "keep;" not in sieve

    def test_generated_header(self):
        config = self._config()
        sieve = generate_sieve_envelope(config)
        assert sieve.startswith("# Generated by autosieve")

    def test_ends_with_newline(self):
        config = self._config()
        sieve = generate_sieve_envelope(config)
        assert sieve.endswith("\n")

    def test_inactive_skipped(self):
        config = self._config(
            rules=[
                Rule(aliases=["alice@example.com"], folder="alias/alice"),
                Rule(aliases=["bob@example.com"], folder="alias/bob", active=False),
            ]
        )
        sieve = generate_sieve_envelope(config)
        assert '"alice"' in sieve
        assert '"bob"' not in sieve

    def test_multi_domain(self):
        config = self._config(
            rules=[
                Rule(aliases=["alice@a.com"], folder="alias/alice"),
                Rule(aliases=["bob@b.com"], folder="alias/bob"),
            ]
        )
        sieve = generate_sieve_envelope(config)
        assert '"a.com"' in sieve
        assert '"b.com"' in sieve
        assert sieve.count('address :domain :is "To"') == 2

    def test_custom_prefix(self):
        config = self._config(
            folder_prefix="mail",
            rules=[Rule(aliases=["alice@example.com"], folder="mail/alice")],
        )
        sieve = generate_sieve_envelope(config)
        assert 'fileinto :create "mail/${alias}"' in sieve

    def test_dispatch_via_generate_sieve(self):
        config = self._config()
        sieve = generate_sieve(config)
        assert '"variables"' in sieve
        assert '"envelope"' not in sieve

    def test_aliases_sorted(self):
        config = self._config(
            rules=[
                Rule(aliases=["zz@example.com"], folder="alias/zz"),
                Rule(aliases=["aa@example.com"], folder="alias/aa"),
            ]
        )
        sieve = generate_sieve_envelope(config)
        aa_pos = sieve.index('"aa"')
        zz_pos = sieve.index('"zz"')
        assert aa_pos < zz_pos

    def test_nested_folder_pattern_generates_rule(self):
        config = self._config(
            rules=[
                Rule(aliases=["shop@example.com"], folder="alias/shops/shop"),
            ]
        )
        sieve = generate_sieve_envelope(config)
        assert 'fileinto :create "alias/shops/${alias}"' in sieve
        assert 'fileinto :create "alias/shops/_other"' in sieve

    def test_mismatched_rule_excluded_from_envelope(self):
        """Rules whose folder basename differs from the alias local-part are silently excluded."""
        config = self._config(
            rules=[
                Rule(aliases=["alice@example.com"], folder="alias/alice"),
                Rule(aliases=["typo@example.com"], folder="alias/typoo"),
            ]
        )
        sieve = generate_sieve_envelope(config)
        assert '"alice"' in sieve
        assert '"typo"' not in sieve
        assert '"typoo"' not in sieve

    def test_dot_separator(self):
        """folder_sep='.' produces dot-separated folder paths."""
        config = self._config(
            folder_sep=".",
            rules=[
                Rule(aliases=["alice@example.com"], folder="alias.alice"),
                Rule(aliases=["bob@example.com"], folder="alias.bob"),
            ],
        )
        sieve = generate_sieve_envelope(config)
        assert 'fileinto :create "alias.${alias}"' in sieve
        assert 'address :domain :is "To" "example.com"' in sieve


class TestPartitionEnvelopeRules:
    def test_matching_rules_go_to_envelope(self):
        rules = [
            Rule(aliases=["alice@example.com"], folder="alias/alice"),
            Rule(aliases=["bob@example.com"], folder="alias/bob"),
        ]
        envelope, fallback = partition_envelope_rules(rules, "alias")
        assert len(envelope) == 2
        assert fallback == []

    def test_mismatched_folder_goes_to_fallback(self):
        rules = [Rule(aliases=["logitell@example.com"], folder="alias/logitel")]
        envelope, fallback = partition_envelope_rules(rules, "alias")
        assert envelope == []
        assert len(fallback) == 1
        assert fallback[0].aliases == ["logitell@example.com"]

    def test_wrong_prefix_goes_to_fallback(self):
        rules = [Rule(aliases=["alice@example.com"], folder="other/alice")]
        envelope, fallback = partition_envelope_rules(rules, "alias")
        assert envelope == []
        assert len(fallback) == 1

    def test_inactive_excluded_from_both(self):
        rules = [Rule(aliases=["alice@example.com"], folder="alias/alice", active=False)]
        envelope, fallback = partition_envelope_rules(rules, "alias")
        assert envelope == []
        assert fallback == []

    def test_nested_folder_matches(self):
        rules = [Rule(aliases=["shop@example.com"], folder="alias/shops/shop")]
        envelope, fallback = partition_envelope_rules(rules, "alias")
        assert len(envelope) == 1
        assert fallback == []

    def test_case_insensitive_match(self):
        rules = [Rule(aliases=["Alice@example.com"], folder="alias/alice")]
        envelope, fallback = partition_envelope_rules(rules, "alias")
        assert len(envelope) == 1
        assert fallback == []

    def test_empty_aliases_goes_to_fallback(self):
        rules = [Rule(aliases=[], folder="alias/alice")]
        envelope, fallback = partition_envelope_rules(rules, "alias")
        assert envelope == []
        assert len(fallback) == 1

    def test_mixed_rules(self):
        rules = [
            Rule(aliases=["alice@example.com"], folder="alias/alice"),
            Rule(aliases=["typo@example.com"], folder="alias/typos"),
        ]
        envelope, fallback = partition_envelope_rules(rules, "alias")
        assert len(envelope) == 1
        assert len(fallback) == 1


class TestGenerateSieveFallback:
    def _config(self, rules, **overrides) -> Config:
        defaults = {
            "headers": ["To"],
            "use_create": True,
            "script_name": "test",
            "explicit_keep": False,
            "match_type": "is",
            "generation_mode": "envelope",
            "folder_prefix": "alias",
            "folder_sep": "/",
            "catch_all_folder": None,
            "rules": rules,
        }
        defaults.update(overrides)
        return Config(**defaults)

    def test_returns_none_when_all_match(self):
        config = self._config([Rule(aliases=["alice@example.com"], folder="alias/alice")])
        assert generate_sieve_fallback(config) is None

    def test_generates_header_block_for_mismatch(self):
        config = self._config([Rule(aliases=["logitell@example.com"], folder="alias/logitel")])
        sieve = generate_sieve_fallback(config)
        assert sieve is not None
        assert 'header :is "To" "logitell@example.com"' in sieve
        assert 'fileinto :create "alias/logitel"' in sieve
        assert "stop;" in sieve

    def test_returns_none_when_no_active_rules(self):
        config = self._config([Rule(aliases=["logitell@example.com"], folder="alias/logitel", active=False)])
        assert generate_sieve_fallback(config) is None

    def test_header_comment(self):
        config = self._config([Rule(aliases=["typo@example.com"], folder="alias/typos")])
        sieve = generate_sieve_fallback(config)
        assert sieve is not None
        assert "autosieve" in sieve
        assert "non-standard" in sieve

    def test_require_fileinto(self):
        config = self._config([Rule(aliases=["typo@example.com"], folder="alias/typos")], use_create=False)
        sieve = generate_sieve_fallback(config)
        assert sieve is not None
        assert '"fileinto"' in sieve
        assert '"mailbox"' not in sieve

    def test_require_mailbox_when_create(self):
        config = self._config([Rule(aliases=["typo@example.com"], folder="alias/typos")])
        sieve = generate_sieve_fallback(config)
        assert sieve is not None
        assert '"mailbox"' in sieve

    def test_ends_with_newline(self):
        config = self._config([Rule(aliases=["typo@example.com"], folder="alias/typos")])
        sieve = generate_sieve_fallback(config)
        assert sieve is not None
        assert sieve.endswith("\n")

    def test_explicit_keep(self):
        config = self._config([Rule(aliases=["typo@example.com"], folder="alias/typos")], explicit_keep=True)
        sieve = generate_sieve_fallback(config)
        assert sieve is not None
        assert sieve.strip().endswith("keep;")

    def test_mixed_excludes_matching_rules(self):
        """Only the non-matching rule should appear in the fallback script."""
        config = self._config(
            rules=[
                Rule(aliases=["alice@example.com"], folder="alias/alice"),
                Rule(aliases=["typo@example.com"], folder="alias/typos"),
            ]
        )
        sieve = generate_sieve_fallback(config)
        assert sieve is not None
        assert "typo@example.com" in sieve
        assert "alice@example.com" not in sieve
