"""Tests for mailfilter.sieve."""

from __future__ import annotations

from mailfilter.config import Config, Rule
from mailfilter.sieve import generate_rule_block, generate_sieve, sieve_quote


class TestSieveQuote:
    def test_plain_string(self):
        assert sieve_quote("hello") == '"hello"'

    def test_backslash(self):
        assert sieve_quote("a\\b") == '"a\\\\b"'

    def test_double_quote(self):
        assert sieve_quote('say "hi"') == '"say \\"hi\\""'

    def test_empty(self):
        assert sieve_quote("") == '""'


class TestGenerateRuleBlock:
    def test_single_alias_single_header(self):
        rule = Rule(aliases=["a@b.com"], folder="F")
        block = generate_rule_block(rule, headers=["To"], match_type="is", use_create=False)
        assert 'header :is "To" "a@b.com"' in block
        assert "anyof" not in block
        assert 'fileinto "F";' in block
        assert "stop;" in block

    def test_multiple_aliases_uses_anyof(self):
        rule = Rule(aliases=["a@b.com", "c@b.com"], folder="F")
        block = generate_rule_block(rule, headers=["To"], match_type="is", use_create=False)
        assert "anyof" in block

    def test_multiple_headers_uses_anyof(self):
        rule = Rule(aliases=["a@b.com"], folder="F")
        block = generate_rule_block(
            rule, headers=["X-Original-To", "Delivered-To"], match_type="is", use_create=False
        )
        assert "anyof" in block
        assert '"X-Original-To"' in block
        assert '"Delivered-To"' in block

    def test_use_create(self):
        rule = Rule(aliases=["a@b.com"], folder="F")
        block = generate_rule_block(rule, headers=["To"], match_type="is", use_create=True)
        assert "fileinto :create" in block

    def test_contains_match(self):
        rule = Rule(aliases=["a@b.com"], folder="F")
        block = generate_rule_block(rule, headers=["To"], match_type="contains", use_create=False)
        assert ":contains" in block

    def test_comment(self):
        rule = Rule(aliases=["a@b.com"], folder="F", comment="My rule")
        block = generate_rule_block(rule, headers=["To"], match_type="is", use_create=False)
        assert block.startswith("# My rule")


class TestGenerateSieve:
    def _config(self, **overrides) -> Config:
        defaults = {
            "headers": ["X-Original-To", "Delivered-To"],
            "use_create": True,
            "script_name": "test",
            "explicit_keep": False,
            "match_type": "is",
            "rules": [
                Rule(aliases=["a@b.com"], folder="Folder/A"),
            ],
        }
        defaults.update(overrides)
        return Config(**defaults)

    def test_require_fileinto(self):
        config = self._config(use_create=False)
        sieve = generate_sieve(config)
        assert 'require ["fileinto"];' in sieve
        assert '"mailbox"' not in sieve

    def test_require_mailbox_when_create(self):
        config = self._config(use_create=True)
        sieve = generate_sieve(config)
        assert '"mailbox"' in sieve

    def test_explicit_keep(self):
        config = self._config(explicit_keep=True)
        sieve = generate_sieve(config)
        assert sieve.strip().endswith("keep;")

    def test_no_keep_by_default(self):
        config = self._config(explicit_keep=False)
        sieve = generate_sieve(config)
        assert "keep;" not in sieve

    def test_generated_header(self):
        config = self._config()
        sieve = generate_sieve(config)
        assert sieve.startswith("# Generated by mailfilter")

    def test_ends_with_newline(self):
        config = self._config()
        sieve = generate_sieve(config)
        assert sieve.endswith("\n")

    def test_multiple_rules(self):
        config = self._config(
            rules=[
                Rule(aliases=["a@b.com"], folder="A"),
                Rule(aliases=["c@b.com"], folder="C"),
            ]
        )
        sieve = generate_sieve(config)
        assert sieve.count("fileinto :create") == 2
        assert sieve.count("stop;") == 2

    def test_sample_output_structure(self, sample_config_path):
        """Generate from sample config and verify structural correctness."""
        from mailfilter.config import load_config

        config = load_config(sample_config_path)
        sieve = generate_sieve(config)

        # Must have require line with both fileinto and mailbox.
        assert 'require ["fileinto", "mailbox"];' in sieve
        # Must have two rule blocks.
        assert sieve.count("fileinto :create") == 2
        assert sieve.count("stop;") == 2
        # Must reference the sample aliases.
        assert "kunde1@maildomain.de" in sieve
        assert "kunde2@maildomain.de" in sieve
        assert "kunde2+alt@maildomain.de" in sieve
